<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pl" sourcelanguage="en">
  <context>
    <name>QObject</name>
    <message>
      <location filename="../scriptingpython.cpp" line="484"/>
      <source>Invalid use of %1 function. Expected %2 arguments, but got %3.</source>
      <translation>Nieprawidłowe użycie funkcji %1. Oczekiwano %2 argumentów, ale otrzymano %3.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="493"/>
      <source>Unknown error from function %1.</source>
      <translation>Nieznany błąd z funkcji %1.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="534"/>
      <source>Could not calculate string representation of the Python object passed as argument to the function %1.</source>
      <translation>Nie można przedstawić obiektu Pythona przekazanego jako argument do funkcji %1 jako reprezentacji ciągu znaków.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="550"/>
      <source>Could not find execution context for function %1. This is a bug of Python plugin. Please report it.</source>
      <translation>Nie można odnaleźć kontekstu wykonania funkcji %1. Jest to błąd wtyczki Pythona. Proszę, zgłoś to.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="575"/>
      <source>Error from Python function %1: %2</source>
      <translation>Błąd z funkcji Pythona %1: %2</translation>
    </message>
  </context>
</TS>
