<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="tr" sourcelanguage="en">
  <context>
    <name>QObject</name>
    <message>
      <location filename="../scriptingpython.cpp" line="484"/>
      <source>Invalid use of %1 function. Expected %2 arguments, but got %3.</source>
      <translation>%1 işlevinin geçersiz kullanımı. Beklenen %2 argümanları, ancak %3 var.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="493"/>
      <source>Unknown error from function %1.</source>
      <translation>%1 fonksiyonundan bilinmeyen hata.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="534"/>
      <source>Could not calculate string representation of the Python object passed as argument to the function %1.</source>
      <translation>%1 işlevine bağımsız değişken olarak geçirilen Python nesnesinin dize gösterimi hesaplanamadı.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="550"/>
      <source>Could not find execution context for function %1. This is a bug of Python plugin. Please report it.</source>
      <translation>%1 işlevinin yürütme içeriği bulunamadı. Bu bir Python eklentisi hatasıdır. Lütfen rapor edin.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="575"/>
      <source>Error from Python function %1: %2</source>
      <translation>Python işlevinden %1 hatası: %2</translation>
    </message>
  </context>
</TS>
